-- liquibase formatted sql

-- changeset dmytrogordiienko:1734193378280-1
CREATE TABLE clients (client_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, client_name VARCHAR(255), CONSTRAINT pk_clients PRIMARY KEY (client_id));

-- changeset dmytrogordiienko:1734193378280-2
CREATE TABLE transactions (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, client_id INTEGER, year VARCHAR(255), month VARCHAR(255), day VARCHAR(255), time time WITHOUT TIME ZONE, amount DOUBLE PRECISION, client_client_id BIGINT, CONSTRAINT pk_transactions PRIMARY KEY (id));

-- changeset dmytrogordiienko:1734193378280-3
ALTER TABLE transactions ADD CONSTRAINT FK_TRANSACTIONS_ON_CLIENT_CLIENT FOREIGN KEY (client_client_id) REFERENCES clients (client_id);

